### ISSUE TITLE
Translations of images broken.

### ISSUE THREAD

**Issue by alatnet** [ppixiv/ppixiv#102] opened 2024-05-15 03:01 UTC
Apparently when trying to translate an image it's pulling from "https://i.pximg.net/img-original/" which is getting a 500 error.
However, right clicking and image and opening it up shows that the image from that is from "https://i.pximg.net/img-master/" and will open up the image fine.

**Comment by EnergoStalin** [comment] 2024-05-18 09:52
I believe it caused by this fix #99 

And this [commit](https://github.com/ppixiv/ppixiv/commit/9997a1dc5ea1eb3b2f1d4e793edf49556e2eb00c) in particular. Without that commit it working for me.

**Comment by ppixiv** [comment] 2024-05-19 06:58
A quick build in Windows (straightforward to adapt for Linux) is:

python -m venv venv
venv\scripts\activate
pip install -r vview\requirements.txt
python -m vview.build.build_ppixiv

I should put build instructions somewhere (along with a description of the other less-known components, like vview, vvpython, vvbrowser...), there just hasn't been much demand for it.

@alatnet Translations should be fixed in r238, give that a try.

**Comment by alatnet** [comment] 2024-05-19 06:59
Yep, it's working fine. ^.^

**Closed** 2024-05-19 07:01 UTC
